### ISSUE TITLE
Unclear where to go

### ISSUE THREAD

**Issue by egingric** [RinglingGameArt/2014-Racing-Game#198]
At start of level, it is unclear which way the player should go. Block off the track to the left by raising it up a little bit so there is a lip that the player has to to drive over, or use some other means to block it off.
![block off](https://f.cloud.github.com/assets/3945065/2500094/10d32a04-b35f-11e3-871f-d9021eab5ca7.jpg)

**Comment by mvolpa1** [comment]
Fixed.

**Comment by egingric** [comment]
This wasn't fixed today when i played your level during RC Candidate.

**Comment by mvolpa1** [comment]
I moved the track upward so it's impossible to go that way now.  The spawn is still moved up enough so players won't see it at the start.
